### ISSUE TITLE
Map/globe being random (in global.html)

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/natureforpeople#1]
<img width="1666" alt="capture d ecran 2019-02-22 a 10 12 20" src="https://user-images.githubusercontent.com/18381609/53262024-65093600-368a-11e9-92bf-06b41e89b9f8.png">
(you probably know about this ;)

**Comment by AhmedAhres** [comment]
Yes! Responsiveness is unfortunately an issue to deal with! It's definitely on the to-do list before the symposium

**Comment by AhmedAhres** [comment]
@charlottegiseleweil Is it still the case?
