### ISSUE TITLE
Design issues pollination.html

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/natureforpeople#4]
Designed for a 17inches screen? The menu overflows, and the 2050 overlays the legend

<img width="1680" alt="capture d ecran 2019-02-27 a 21 57 20" src="https://user-images.githubusercontent.com/18381609/53544426-d3128a80-3ada-11e9-8a1b-6599533577ab.png">

**Comment by charlottegiseleweil** [comment]
this is related to menu issue in index.html --> not responsive to screensize

**Comment by AhmedAhres** [comment]
Can you check if the "2050" still overlays?

**Comment by charlottegiseleweil** [comment]
still does :'(
