### ISSUE TITLE
NCP 2015&2050 Tab: map functionalities broken

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/natureforpeople#5]
Span and zoom impossible

**Comment by AhmedAhres** [comment]
Could you be more specific? We don't see a zoom problem here

**Comment by charlottegiseleweil** [comment]
I have zero panning or zooming ability. Running Chrome 72.0.3626.119 on MacOS 10.13.6

**Comment by AhmedAhres** [comment]
@charlottegiseleweil could you try to run it on Firefox? Chrome is blocking a lot of functionalities for some reason. Could you please try it on Firefox and tell me if the issue still appears?

**Comment by charlottegiseleweil** [comment]
seems fixed, even on Chrome!
