### ISSUE TITLE
Navbar not responsive to screensize

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/natureforpeople#6]
Hey @AhmedAhres , I was re-rewriting the navar to make it repsonsive, but didn't want to mess up with your links so wasn't sure about pushing it: but here's a suggested code to fix navbar:

~~~~  
<head>
<!--w3-->
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<!-- Navbar -->
<div class="w3-top">
    <div class="nav-global w3-bar w3-theme-d2 w3-left-align">
      <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-hover-white w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
      <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-grey nav-link" onclick="activate_nature_button()><i class="fa fa-home w3-margin-right"></i>     WHERE NATURE HELPS US MOST TODAY?</a>
      <a href="people.html" class="w3-bar-item w3-button w3-hide-small w3-hover-grey nav-link" onclick="activate_risk_button()><i class="fa fa-home w3-margin-right"></i>    WHERE ARE PEOPLE AT RISK IN THE FUTURE?</a>` 

      

      <a href="#" class="w3-bar-item w3-button w3-hide-small w3-right w3-hover-grey" title="info-button">&#9432</a>
      <a id="About" href="viz/about.html" onclick="openAbout()" class="w3-bar-item w3-button w3-hide-small w3-right w3-hover-grey">
      About</a>

  </div>


<!-- Alternative to about.html: if we want about.html to be embedded in the main page "overlay" style

  <script>
function openAbout() {
  document.getElementById("#About").style.width = "100%";
  $("#About").load("static/about.html");
}
function closeAbout() {
   document.getElementById("#About").style.width = "0%";
</script>
~~~~ 

The problem was:

<img width="805" alt="capture d ecran 2019-02-27 a 17 32 43" src="https://user-images.githubusercontent.com/18381609/53588087-fa9c3e00-3b40-11e9-803c-cdc283dde9a8.png">
<img width="1680" alt="capture d ecran 2019-02-27 a 17 32 32" src="https://user-images.githubusercontent.com/18381609/53588088-fa9c3e00-3b40-11e9-93d8-01b560ee8669.png">

My code leads to:
<img width="1737" alt="capture d ecran 2019-02-28 a 10 11 12" src="https://user-images.githubusercontent.com/18381609/53588188-36cf9e80-3b41-11e9-9955-734dd277fc4c.png">

We'll need to add the navbar, once finalized, onto viz_risk.html as well @annfr542 !

**Comment by annfr542** [comment]
I'm working och creating the navbar on viz_risk.html as well, will push it tomorrow

**Comment by charlottegiseleweil** [comment]
Perhaps @annfr542, wait till we have it finalized (or fix it if you feel like it ;) )because the current navbar is not working so well!

**Comment by annfr542** [comment]
I already started to create a new one that is fitting in better with our design, but maybe I should stop ?

**Comment by annfr542** [comment]
So I added my navbar now, worst case I just remove it :)

**Comment by charlottegiseleweil** [comment]
Rockstar!


Charlotte Weil
The Natural Capital Project, Stanford University
« Be the change you wish to see in the world »   [Mahatma Gandhi]

**Comment by charlottegiseleweil** [comment]
Rockstar @annfr542 ! 

I think we need the make the navbar coherent in both part of the viz. Since  Anna's is work, and Ahmed had this responsiveness issue, why don't we just copy Anna's in @AhmedAhres's part? 

However @annfr542 we need to add (probably top right for coehrence between all pages) an "About" tab, linking to about.html or a pop-up About window, and and "info-button" ( just use this: `&#9432` ), which leads to pop-up explaining how to read the map is the current tab 

Great work y'all!

**Comment by AhmedAhres** [comment]
Yes we can do that @charlottegiseleweil ! I'll have a look at this responsiveness issue :)

**Comment by charlottegiseleweil** [comment]
I guess you don't need to look into it @AhmedAhres if you just swap for @annfr542's menus.. up to you!

**Comment by AhmedAhres** [comment]
@charlottegiseleweil Anna's menus are indeed great for responsive, but design-wise they do not seem to be good for our viz. It does look amazing on their's though. I will focus on fixing the responsiveness.

**Comment by AhmedAhres** [comment]
@charlottegiseleweil I added your menu in the global map and changed ours in pollination and WQ to be responsive. Could you have a look if possible?
